<link href="<?php echo $this->baseURL();?>/public/css/project.css" media="screen" rel="stylesheet" type="text/css">
<ul class="project-seg-wrap">
    <li class="project-list-wrap">
        <ul class="project-list">
            <li class="project">
                <div class="preview">
                    <img src="<?php echo $this->baseURL();?>/public/images/project/1.png"/>
                </div>
            </li>
        </ul>
    </li>
</ul>