<link href="<?php echo $this->baseUrl();?>/public/css/project.css" media="screen" rel="stylesheet" type="text/css">
<ul class="project-seg-wrap">
    <li class="project-list-wrap">
        <ul class="project-list">
            <?php foreach($this->projects as $project) : ?>
            <li class="project-wrap">
                <div style="width: <?php echo $project->width;?>px; height: <?php echo $project->height;?>px;" class="project"
                     id="<?php echo $project->prid;?>">
                    <p class="photo">
                        <img src="<?php echo $this->baseUrl()
                                .'/public/images/project/'
                                .$project->photo.'.png';?>"/>
                    </p>
                    <p class="title">
                        <span class="caption"><?php echo $project->caption;?></span>
                        <br>
                        <?php echo $project->title;?>
                    </p>
                    <p class="data"><?php echo $project->data;?></p>
                </div>
            </li>
            <?php endforeach; ?>
            <li class="place-holder"></li>
        </ul>
    </li>
</ul>