<?php
session_start();

$this->headTitle($this->title);
$this->headLink()->prependStylesheet($this->baseUrl().'/public/css/index.css');
$this->headScript()->appendFile($this->baseUrl().'/public/js/index.js');

$keys = array("Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P");
$keys2 = array("A", "S", "D", "F", "G", "H", "J", "K", "L");
$keys3 = array("Z", "X", "C", "V", "B", "N", "M", "<", ">");
?>

<div id="index-wrap">
    <div class="navigate-area-outer">
        <div class="navigate-area">
            <div class="navigate-tips">
                use keyboard to navigate
            </div>
            <div class="navigate-menu P">
                <ul>
                    <li class="menu-item rounded shadow3 post"><div class="tags rounded shadow3">post</div></li>
                    <li class="menu-item rounded shadow3 project"><div class="tags rounded shadow3">project</div></li>
                    <li class="menu-item rounded shadow3 public"><div class="tags rounded shadow3">public</div></li>
                    <li class="nav-str"></li>
                </ul>
            </div>
            
            <div class="navigate-menu B">
                <ul>
                    <li class="menu-item rounded shadow3  blog"><div class="tags rounded shadow3">blog</div></li>
                    <li class="nav-str"></li>
                </ul>
            </div>
            <div class="navigate-menu G">
                <ul>
                    <li class="menu-item rounded shadow3  game"><div class="tags rounded shadow3">game</div></li>
                    <li class="nav-str"></li>
                </ul>
            </div>
            <div class="navigate-menu F">
                <ul>
                    <li class="menu-item rounded shadow3  fun"><div class="tags rounded shadow3">fun</div></li>
                    <li class="menu-item rounded shadow3 "><div class="tags rounded shadow3">fightclub</div></li>
                    <li class="nav-str"></li>
                </ul>
            </div>
            <div class="navigate-menu C">
                <ul>
                    <li class="menu-item rounded shadow3 "><div class="tags rounded shadow3">contact</div></li>
                    <li class="nav-str"></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="key-board rounded shadow3">       
        <ul>
            <li id="key-tab" class="key-element-wrapper key-size-tab">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Tab
                    </div>
                </div>
            </li>
            <?php foreach($keys AS $key): ?>
            <li id="key-<?php echo $key;?>" class="key-element-wrapper key-size-normal">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3"
                        name="<?php echo $key;?>">
                        <?php echo $key;?>
                    </div>
                </div>
            </li>
            <?php endforeach;?>
            
            <li id="key-backspace" class="key-element-wrapper key-size-backspace">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        <-
                    </div>
                </div>
            </li>
            <li id="key-caps" class="key-element-wrapper key-size-caps">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Caps
                    </div>
                </div>
            </li>
            <?php foreach($keys2 AS $key): ?>
            <li id="key-<?php echo $key;?>" class="key-element-wrapper key-size-normal">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3"
                        name="<?php echo $key;?>">
                        <?php echo $key;?>
                    </div>
                </div>
            </li>
            <?php endforeach;?>
            
            <li id="key-enter" class="key-element-wrapper key-size-enter">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        enter
                    </div>
                </div>
            </li>
            <li id="key-shift-left" class="key-element-wrapper key-size-shift-left">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Shift
                    </div>
                </div>
            </li>
            <?php foreach($keys3 AS $key): ?>
            <li id="key-<?php echo $key;?>" class="key-element-wrapper key-size-normal">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3"
                        name="<?php echo $key;?>">
                        <?php echo $key;?>
                    </div>
                </div>
            </li>
            <?php endforeach;?>
            
            <li id="key-shift-right" class="key-element-wrapper key-size-shift-right">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Shift
                    </div>
                </div>
            </li>
            
            <li id="key-ctrl" class="key-element-wrapper key-size-control">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Ctrl
                    </div>
                </div>
            </li>
            
            <li id="key-option" class="key-element-wrapper key-size-option">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Option
                    </div>
                </div>
            </li>
            
            <li id="key-command" class="key-element-wrapper key-size-command">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Cmd
                    </div>
                </div>
            </li>
            <li id="key-space" class="key-element-wrapper key-size-space">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3">
                        Space
                    </div>
                </div>
            </li>
            <li id="key-messages" class="key-element-wrapper key-size-message">
                <div class="key-element">
                    <div class="key-element-content rounded2 shadow3 special-key3">
                        Message
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--
<div id="msg-box-wrapper">
    <div class="msg-box">
        <span class="title">Qianze Zhang has acknowledged that </span>
        <span class="text"></span>
    </div>
</div>-->
<div class="overlay"></div>
<!--
<div id="nav-string-wrapper">
    <div class="nav-string-content rounded2 shadow3">
    </div>
    <div class="nav-string-tri"></div>
</div>-->