<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Plutoless Studio');

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl().'/public/css/page.css');?>
        <?php $this->headScript()->prependFile($this->baseUrl().'/public/js/common.js');?>
        <?php $this->headScript()->prependFile($this->baseUrl().'/public/js/jquery.color.js');?>
        <?php $this->headScript()->prependFile($this->baseUrl().'/public/js/jquery.easing.1.3.js');?>
        <?php $this->headScript()->prependFile($this->baseUrl().'/public/js/jquery-1.8.0.min.js');?>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
        <link rel="shortcut icon" href="<?php echo $this->baseURL();?>/images/favicon.ico">
    </head>
    <body>
        
        <div id="header">
          <div class="logo">
              
            <div id="msg-box" class="msg-box rounded color5">
                <img src="<?php echo ($this->baseUrl().'/public/images/msg2/headphones.png'); ?>"/>
            </div>
            <div class="tip"></div>
            <img src="<?php echo ($this->baseUrl().'/public/images/logo.png'); ?>"></img>
          </div>
        </div>
        <div id="navigation">
            <ul>
                <li>
                    <div class="holding color5"></div>
                    <div class="nav-link">
                      <a href="<?php echo $this->baseURL();?>">
                          <span>Index</span>
                      </a>
                    </div>
                </li>
                |
                <li>
                    <div class="holding color5"></div>
                    <div class="nav-link">
                      <a href="post">
                          <span>Posts</span>
                      </a>
                    </div>
                </li>
                |
                <li>
                    <div class="holding color5"></div>
                    <div class="nav-link">
                      <a href="projects">
                          <span>Projects</span>
                      </a>
                    </div>
                </li>
                |
                <li>
                    <div class="holding color5"></div>
                    <div class="nav-link">
                      <a href="fun">
                          <span>Fun</span>
                      </a>
                    </div>
                </li>
                |
                <li>
                    <div class="holding color5"></div>
                    <div class="nav-link">
                      <a href="contact">
                          <span>Contact</span>
                      </a>
                    </div>
                </li>
            </ul>
        </div>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="bottom">
            © 2013 plutoless-studio
        </div>
    </body>
</html>