<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Plutoless Studio');

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/page.css');?>
        <?php echo $this->headScript()->prependFile($this->baseUrl().'/../library/js/jquery-1.7.2.min.js');?>
    </head>
    <body>
        <!--
        <div id="header">
          <img src="<?php echo ($this->baseUrl().'/images/logo.png'); ?>"></img>
        </div>-->
        <div id="content">
            <?php echo $this->layout()->content; ?>
            <div id="bottom">
                
            </div>
        </div>
    </body>
</html>