<div class="menu-column">
    <div class="menu-block">
        <ul>
            <?php foreach($this->postTypes as $type): ?>
            <li>
                <?php echo $type->ptype; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<div class="center-column">
    <div class="post-list-wrap">
        <ul class="post-list">
            <?php foreach($this->pagePosts as $post) : ?>
            <li id="<?php echo $post->pid; ?>" class="post">
                <div class="titleBar">
                    <div class="title inline"><?php echo $this->escape($post->title);?></div>
                </div>
                <div class="content"><?php echo nl2br($post->content);?></div>
                <!--<div class="time"><?php echo date("M d, Y", strtotime($this->escape($post->ts)));?></div>-->
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="post-control-wrap">
        <div class="control-key-wrap" name="prev">
            <div class="control-key-frame rounded2 shadow4">
                Prev
            </div>
        </div>
        <div class="control-key-wrap" name="next">
            <div class="control-key-frame rounded2 shadow4">
                Next
            </div>
        </div>
        <div class="control-key-wrap" name="home">
            <div class="control-key-frame rounded2 shadow4">
                Home
            </div>
        </div>
    </div>
</div>

<div class="menu-column">
    <div class="menu-block">
    <div class="return menu-content">
    </div>
    </div>
    <div class="menu-block">
    <div class="refresh menu-content">
    </div>
    </div>
</div>