<br /><br />
<div id="view-content">
	<p>View script for controller <b>Post</b> and script/action name <b>month</b></p>
</div>



<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->monthlyPosts as $post) : ?>
<tr>
    <td><?php echo $this->escape($post->text);?></td>
    <td><?php echo $this->escape($post->title);?></td>
</tr>
<?php endforeach; ?>
</table>